sudo: required

services:
    - docker

before_install:
    - docker pull cakephpfr/3.x

script:
    - docker-compose run -d
    - docker-compose run php curl -sS https://getcomposer.org/installer | php
    - docker-compose run php ./composer.phar require 'cakephp/cakephp-codesniffer:2.x'
    - docker-compose run php ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot

notifications:
    email: false
